services:
  persons-backend:
    build:
      context: backend
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      db_url: "jdbc:postgresql://persons-db:5432/persons"
      app_port: 8081
    depends_on:
      - persons-db

  persons-db:
    build:
      context: db
    restart: unless-stopped
    ports:
      - 5777:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: persons
    volumes:
      - main_db:/var/lib/postgresql

volumes:
  main_db:
